
# General settings
force_reproducibility: true
device: "cpu"

# Training settings
lr: 0.0005  
batch_size: 64  
num_epochs: 8

# Optimizer settings
optim: "adamw"

# Logging and saving
avoid_wandb: true
save_model: true
